# Generated by Django 6.0.3 on 2026-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworksubmission",
            name="files",
            field=models.FileField(blank=True, null=True, upload_to="submissions/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="lessons/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
