# Generated by Django 6.0.3 on 2026-04-10 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0002_alter_homeworksubmission_files_alter_lesson_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='messages',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ls.homeworksubmission')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
