export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  profile: "/profile",
  dashboard: "/dashboard",
  courses: "/courses",
  myCourses: "/my-courses",
  newCourse: "/courses/new",
  course: (id: string) => `/courses/${id}`,
  editCourse: (id: string) => `/courses/${id}/edit`,
  newLesson: (id: string) => `/courses/${id}/lessons/new`,
  lesson: (id: string) => `/lessons/${id}`,
  editLesson: (id: string) => `/lessons/${id}/edit`,
  newHomework: (lessonId: string | number) =>
    `/lessons/${lessonId}/homeworks/new`,
  homework: (id: string | number) => `/homeworks/${id}`,
  editHomework: (id: string | number) => `/homeworks/${id}/edit`,
  api: {
    login: "/api/auth/login/",
    logout: "/api/auth/logout/",
    register: "/api/auth/register/",
    tokenRefresh: "/api/auth/token/refresh/",
    profile: "/api/users/me/",
    courses: "/api/courses/",
    myCourses: "/api/courses/my/",
    course: (id: string) => `/api/courses/${id}/`,
    enrollments: "/api/enrollments/",
    lessons: (courseId: string) => `/api/lessons/?course_id=${courseId}`,
    lesson: (id: string) => `/api/lessons/${id}/`,
  },
} as const;
